services:
  # Создаем контейнер
  postgres:
    image: postgres:15
    #Название контейнера
    container_name: DB_for_site
    env_file:
      - .env
    #Необходимые данные для подключения
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    #Указываем где будет хранится информация
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #Указываем какие SQL команды должны выполнить при запуске контейнера (все что находится в migrations)
      - ./migrations:/docker-entrypoint-initdb.d
    # Перезапускаем если контейнер падает
    restart: unless-stopped
    # Проверяет живой ли контейнер
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DBNAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: project_redis
    restart: unless-stopped

  app:

    build:
      context: .
      dockerfile: ./backend-node/Dockerfile

    container_name: project_backend

    env_file:
      - .env

    ports:
      - "8080:8080"

    depends_on:

      postgres:
        condition: service_healthy

      redis:
        condition: service_started

    restart: unless-stopped

    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      
volumes:
  postgres_data:
    